### ISSUE TITLE
Error on generating pdg

### ISSUE THREAD

**Issue by paolopc67** [GM-Script-Writer-62850/PHP-Scanner-Server#21]
I have just installed my hp scanner and it work without problems but the web interface is not able to generate pdf files despite the presence of the php fpdf library. I have ubuntu 14.04 and I have verified that when I try to download the scanned file in pdf format it launches after selecting the correct dimension a new tab within the current browser with a blank image. This behavior is identical in different browser safari Firefox chrome and ie. The debug console doesn't give any more information

**Comment by GM-Script-Writer-62850** [comment]
confirmed, looks like a JS issue, main.js line 864, files.quantity is undefined
seems like a bug from merging the new printing feature with the pdf one

**Comment by GM-Script-Writer-62850** [comment]
this should solve this issue
[commit](/GM-Script-Writer-62850/PHP-Scanner-Server/commit/d56f60200051b2f31813f3937e8578c5ec737493)

**Comment by GM-Script-Writer-62850** [comment]
[revised](/GM-Script-Writer-62850/PHP-Scanner-Server/commit/e30a5b08c1278622463554e92a23cc88c73ff547) for better efficiency

thinks for bringing this to my attention i ran into it the other day and got distracted and forgot to fix it
