### ISSUE TITLE
Saved Settings

### ISSUE THREAD

**Issue by yvanmoriame** [GM-Script-Writer-62850/PHP-Scanner-Server#22]
Hi,  first of all great job  !
To see what is the active settings, it would be interesting that when selecting the name of a configuration, that name is returned to the field 
 
Thanks
Yvan

![settings](https://cloud.githubusercontent.com/assets/11893300/7098238/367c3eb0-dfde-11e4-9998-f1bbea2beaa3.jpg)

**Comment by GM-Script-Writer-62850** [comment]
so you are asking for a tool tip listing the settings/configs?

**Comment by yvanmoriame** [comment]
No,  just see what my active/selected setting/configs is.
eg see attached picture, when i select "normal.cfg",         normal.cfg as to be returned to the surrounded field

**Comment by GM-Script-Writer-62850** [comment]
for the purpose of changing the settings on the config or just knowing what you clicked?

**Comment by GM-Script-Writer-62850** [comment]
btw why did you blank out your domain name in the address bar? it is kinda displayed in the footer of the page that is a private address unless you are in your house that is useless to anyone

**Comment by yvanmoriame** [comment]
1. both are valid 
2. why did you blank out your domain name in the address bar?     routinely

**Comment by GM-Script-Writer-62850** [comment]
Replace this line (highlighted in this link)
https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/blob/master/res/inc/scan.php#L182
with this one
```
echo "'set_save':'$id'";
```
see if that does what you want

**Comment by GM-Script-Writer-62850** [comment]
i noticed a security issue so i fixed that and put your request in there
https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/commit/7fcbd126c1766bc1e362399181e17ad846d037bc

**Comment by yvanmoriame** [comment]
Sorry, with the modified code, the name of the config come in the field but the settings are not changed.

**Comment by GM-Script-Writer-62850** [comment]
yea, im trying to fix breakage and stuff, done 5 commits so far trying to fix another issue with it specal character related

**Comment by GM-Script-Writer-62850** [comment]
try this 
https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/blob/master/res/inc/scan.php#L176-188

**Comment by yvanmoriame** [comment]
That's it, good works
Thanks a lot. Greetings from Belgium
Yvan

**Comment by GM-Script-Writer-62850** [comment]
i spent about 30-60min trying to properly escape the save name for js to fill out
just to realize after i finally did it that i could have told the js to read the test vale on the label after remembering i made a function to escape js after 30 min
current complicated solution:
```
"'set_save':'".html(js($id))."'});".
```
simple fool proof solution:
```
"'set_save':this.textContent});".
```

note to self: don't code on a empty stomach

**Comment by yvanmoriame** [comment]
Ok,

The simple ... solution works.
Another maybe stupid question:

What is the useof"Selectregion" in the "scan page"as theupdatebuttondoes 
nothing. In the "Edit page",noproblem, you can selectand save thedesired 
scan region

Yvan




------ Message d'origine ------
De : "GM-Script-Writer-62850" <notifications@github.com>
À : "GM-Script-Writer-62850/PHP-Scanner-Server" 
<PHP-Scanner-Server@noreply.github.com>
Cc: "yvanmoriame" <yvan.moriame@gmail.com>
Envoyé 11/04/2015 02:20:18
Objet : Re: [PHP-Scanner-Server] Saved Settings (#22)

>i spent about 30-60min trying to properly escape the save name for js 
>to fill out
>just to realize after i finally did it that i could have told the js to 
>read the test vale on the label after remembering i made a function to 
>escape js after 30 min
>current complicated solution:
>
>"'set_save':'".html(js($id))."'});".
>simple fool proof solution:
>
>"'set_save':this.textContent});".
>note to self: don't code on a empty stomach
>
>—
>Reply to this email directly or view it on GitHub.
>

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by GM-Script-Writer-62850** [comment]
you can manually adjust the crop or scanner bAY SELECTION AREA (caps lock key is a traitor)
it is good for fine tuning when you don't want to use a mouse over a few pixel adjustment

**Comment by GM-Script-Writer-62850** [comment]
if you need to save a certain scan size use the paper config settings

**Comment by GM-Script-Writer-62850** [comment]
oh it looks like i missed some outdated code in the setting saver for scans that is no longer needed since i added the ruler feature

**Comment by yvanmoriame** [comment]
ok i see how to use

1st    scan full size (preview)
2nd   select desired area click update
3rd    click scan      and only the desired area is scanned

Thanks regards
Yvan

------ Message d'origine ------
De : "GM-Script-Writer-62850" <notifications@github.com>
À : "GM-Script-Writer-62850/PHP-Scanner-Server" 
<PHP-Scanner-Server@noreply.github.com>
Cc: "yvanmoriame" <yvan.moriame@gmail.com>
Envoyé 11/04/2015 02:38:07
Objet : Re: [PHP-Scanner-Server] Saved Settings (#22)

>you can manually adjust the crop or scanner bAY SELECTION AREA (caps 
>lock key is a traitor)
>it is good for fine tuning when you don't want to use a mouse over a 
>few pixel adjustment
>
>—
>Reply to this email directly or view it on GitHub.
>

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by GM-Script-Writer-62850** [comment]
step 2 can be done with the mouse only on the preview image icon area

**Comment by yvanmoriame** [comment]
Ok.

------ Message d'origine ------
De : "GM-Script-Writer-62850" <notifications@github.com>
À : "GM-Script-Writer-62850/PHP-Scanner-Server" 
<PHP-Scanner-Server@noreply.github.com>
Cc: "yvanmoriame" <yvan.moriame@gmail.com>
Envoyé 11/04/2015 02:50:51
Objet : Re: [PHP-Scanner-Server] Saved Settings (#22)

>step 2 can be done with the mouse only on the preview image icon area
>
>—
>Reply to this email directly or view it on GitHub.
>

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by yvanmoriame** [comment]
ok, let me know,   i go to sleep because it's    3:00  local time

Yvan
------ Message d'origine ------
De : "GM-Script-Writer-62850" <notifications@github.com>
À : "GM-Script-Writer-62850/PHP-Scanner-Server" 
<PHP-Scanner-Server@noreply.github.com>
Cc: "yvanmoriame" <yvan.moriame@gmail.com>
Envoyé 11/04/2015 02:45:33
Objet : Re: [PHP-Scanner-Server] Saved Settings (#22)

>oh it looks like i missed some outdated code in the setting saver for 
>scans that is no longer needed since i added the ruler feature
>
>—
>Reply to this email directly or view it on GitHub.
>

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by GM-Script-Writer-62850** [comment]
the reason the settings saver does not store crops or region selecting is i suspect that if you apply one with a region selection after a scan that the region select feature was used on would cause a unpredicted scan area would get used so to avoid that bug that feature does not exist

i managed to find a issue with saving after scanning and get a fix for that here

**Comment by yvanmoriame** [comment]
Ok, I am waiting to hear from you.
For me,  at program startup the selectregion function should be disabled 
and only activated after a preview scan, the function only makes sense 
if you know the size of the specific area to scan which is very rare.
After a preview scan if you want to select and save a specific region 
that's can be achieved via the tab "Edit" what seems to me more logical.
Thus is the selectregion function really needed in the tab "Scan" ?

Regards
Yvan

------ Message d'origine ------
De : "GM-Script-Writer-62850" <notifications@github.com>
À : "GM-Script-Writer-62850/PHP-Scanner-Server" 
<PHP-Scanner-Server@noreply.github.com>
Cc: "yvanmoriame" <yvan.moriame@gmail.com>
Envoyé 11/04/2015 03:53:55
Objet : Re: [PHP-Scanner-Server] Saved Settings (#22)

>the reason the settings saver does not store crops or region selecting 
>is i suspect that if you apply one with a region selection after a scan 
>that the region select feature was used on would cause a unpredicted 
>scan area would get used so to avoid that bug that feature does not 
>exist
>
>i managed to find a issue with saving after scanning and get a fix for 
>that here
>
>—
>Reply to this email directly or view it on GitHub.
>

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by GM-Script-Writer-62850** [comment]
the ruler feature makes it usable on the pre scan page
eg i found a rare pokemon card let me put this on ebay
my scanner is slow and my camaer battery is dead lets only scan the card and not the entire baytro save time
gets ruler 89mm by 63mm (~ 3.5 x 2.5 US inches)

now you don't have to make a paper size labeled pokemon card for that one card you can just use the ruler feature and the select region feature 

the select area scan is also useful if you do a quick scan then want to do a high res scan of a part of that

**Comment by yvanmoriame** [comment]
Oh yes, that's right, I didnot remember the speed of my firstscanner.

Regards, have a goodweekend
Yvan

------ Message d'origine ------
De : "GM-Script-Writer-62850" <notifications@github.com>
À : "GM-Script-Writer-62850/PHP-Scanner-Server" 
<PHP-Scanner-Server@noreply.github.com>
Cc: "yvanmoriame" <yvan.moriame@gmail.com>
Envoyé 11/04/2015 11:59:18
Objet : Re: [PHP-Scanner-Server] Saved Settings (#22)

>the ruler feature makes it usable on the pre scan page
>eg i found a rare pokemon card let me put this on ebay
>my scanner is slow and my camaer battery is dead lets only scan the 
>card and not the entire baytro save time
>gets ruler 89mm by 63mm (~ 3.5 x 2.5 US inches)
>
>now you don't have to make a paper size labeled pokemon card for that 
>one card you can just use the ruler feature and the select region 
>feature
>
>the select area scan is also useful if you do a quick scan then want to 
>do a high res scan of a part of that
>
>—
>Reply to this email directly or view it on GitHub.
>

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by GM-Script-Writer-62850** [comment]
you to, happy scanning
