### ISSUE TITLE
Scanner access enabler

### ISSUE THREAD

**Issue by Caysho** [GM-Script-Writer-62850/PHP-Scanner-Server#24]
If a usb scanner is unplugged and plugged in again, the enabler needs to be run again.
Can it be added to the udev rule ?

I presume then it would not be needed in /etc/rc.local

**Comment by GM-Script-Writer-62850** [comment]
the udev rule should replace the enabler
make sure you have the current version installed of the scanner software
the ID of scanners can change (non-HP ones in my exp) i know at some point i made the scanner detected and change the id to the new one, before this was done you had to recheck for scanners to get it working

the udev rule is made by the main installer, not the updater
* im going off my memory which i not always 100% accurate

**Comment by Caysho** [comment]
The clone of this git repository is current.
The scanner is a Canon, it is very new and does not have support in the current Ubuntu repositories.
Support is via PPA at https://launchpad.net/~rolfbensch/+archive/ubuntu/sane-git

After unplugging and plugging in the scanner, running the udev rule script gives the following output:

You have rules, but something is different
  /etc/udev/rules.d/40-scanner.rules has:
	#---START-OF-FILE---
     1	Bus 004 Device 004: ID 04a9:190f Canon, Inc. 
	#----END-OF-FILE----
These are the new rules:
	#---START-OF-FILE---
     1	Bus 004 Device 007: ID 04a9:190f Canon, Inc. 
	#----END-OF-FILE----
No action taken, you can edit /etc/udev/rules.d/40-scanner.rules as you see fit

However, running the enabler allows it to work again.

**Comment by GM-Script-Writer-62850** [comment]
the rule was not created cause the script avoids altering you existing configs
however it looks like when i made that script i forgot to have it tell you the rule it would have added

if you had said rule it would/should work, but you lack said rule

**Comment by GM-Script-Writer-62850** [comment]
http://pastebin.com/NTsSKR4z
can you post the output of this one so i can find the issue?

**Comment by Caysho** [comment]
Debug: genesys:libusb:004:007
Debug: 004:007
Debug: Bus 004 Device 007: ID 04a9:190f Canon, Inc. 
You have rules, but something is different
  /etc/udev/rules.d/40-scanner.rules has:
	#---START-OF-FILE---
     1	Bus 004 Device 004: ID 04a9:190f Canon, Inc. 
	#----END-OF-FILE----
These are the new rules:
	#---START-OF-FILE---
     1	Bus 004 Device 007: ID 04a9:190f Canon, Inc. 
	#----END-OF-FILE----
No action taken, you can edit /etc/udev/rules.d/40-scanner.rules as you see fit

**Comment by Caysho** [comment]
The one with Device 004 would have been created when I first ran the script last weekend.
Unplugging the scanner and plugging it in again gives it a new Device ID of 007

**Comment by GM-Script-Writer-62850** [comment]
http://pastebin.com/n4jtv3Gk
try that script see if it makes a rule that looks right and works
if you don't want to make the file manually delete `/etc/udev/rules.d/40-scanner.rules`
`sudo rm /etc/udev/rules.d/40-scanner.rules`
your current file is useless and was made by my broken code, no idea when it broke but it did

**Comment by Caysho** [comment]
chown: cannot access ‘/dev/bus/usb/04a9’: No such file or directory
chown: cannot access ‘190f’: No such file or directory
/etc/udev/rules.d/40-scanner.rules is good to go

looking in the usb devices:
bananapi@lemaker:~/PHP-Scanner-Server$ ls /dev/bus/usb/00
001/ 002/ 003/ 004/ 005/ 

Each of these usb directories has a single file 001 listed as a character device:

bananapi@lemaker:~/PHP-Scanner-Server$ ls /dev/bus/usb/001/ -la
total 0
drwxr-xr-x 2 root root     60 Jan  1  1970 .
drwxr-xr-x 7 root root    140 Jan  1  1970 ..
crw-rw-r-- 1 root root 189, 0 Jan  1  2010 001

**Comment by GM-Script-Writer-62850** [comment]
try this one
http://pastebin.com/fxytaDJG

*the only scanner i have to test this is not plugged in and need BIOS settings changed

i think this is what you should have in the rule file
```
cat /etc/udev/rules.d/40-scanner.rules
SUBSYSTEMS=="usb", ATTRS{idVendor}=="04a9", ATTRS{idProduct}=="190f", ENV{libsane_matched}="yes", GROUP="lp"
```

**Comment by GM-Script-Writer-62850** [comment]
This one should work
http://pastebin.com/fttFAj7x
if it gives no errors and you can unplug and plug it back a few times without issues i will update the file to this one

**Comment by Caysho** [comment]
The script at http://pastebin.com/fttFAj7x works.
Configure, Search For Scanners button finds it.

I have removed the access enabler from running at boot.
After rebooting, unplugging and plugging a few times, I can still scan.

**Comment by GM-Script-Writer-62850** [comment]
Thanks for letting me know that script broke
