### ISSUE TITLE
Integrated Printer

### ISSUE THREAD

**Issue by kneiser** [GM-Script-Writer-62850/PHP-Scanner-Server#43]
I have a printer setup in CUPS on my server, printing from server is working. I have the Integrated Printer option in the config.ini set to "1". PHP-Scanner-Server can detect the printer. When I attempt to print a scanned document a browser (Firefox) window opens and shows the printers defined on my Linux client computer rather than the printer defined in my LAMP server.

What am I doing wrong?

**Comment by GM-Script-Writer-62850** [comment]
When you click print you should get this question:
<img src="https://i.imgur.com/M68WZW4.png"/>
When you click Cancel you should get this (This is what it sounds like you want):
<img src="https://i.imgur.com/JamsSQW.png"/>
however if you click OK this is what you should get (this sounds like what you are getting):
<img src="https://i.imgur.com/8oWH4Aq.png"/>
How are you answering the prompt?

**Comment by kneiser** [comment]
Ok now i see where I got confused. Part of my problem was where I was trying to get things to work. I now see that the indiviual scanned items have a printer button. I get the behaviour you referenced above. On the scanned files page, in the bulk operations section, the printer button behaves differently. When selecting all scanned files, the printer button does not allow one to use the server defined printer? It wants to print to the client computer printer dialogue. Is there any way of changing it to the same behaviour as the individual scanned item printer button?

**Comment by GM-Script-Writer-62850** [comment]
I am not sure if i should label that as a bug or enhancement

**Comment by kneiser** [comment]
I am not sure either. As a user I would have an expectation that the printer button functionality would be the same for individual scans and bulk operation scans. When using the bulk operations printer button; a user would be selecting more than one scanned image, push the bulks operations print button, expecting to choose a user client workstation or server defined printer. Currently when doing the bulk operations print; a print preview window appears, followed by a browser printer dialogue showing the users' workstation printer list. In my use case; the server printer is CUPS-PDF (I have a cloud service running on my server), The CUPS-PDF directory is accessible by the cloud service, I scan in muliple document pages - would like to do a bulk print of all images to a PDF file, move the resulting PDF to somewhere else in the cloud service without having to download a PDF file from the scanner server and not upload it to the cloud service. **BTW:** I have "somewhat" integrated the "Scanner Server" in to the cloud service so it looks like one of the cloud applications, it looks really good!

**Comment by GM-Script-Writer-62850** [comment]
Can you try a patch to see if everything works
Change this line:
https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/blob/master/index.php#L138
to:
`'bulk'=>"PDF_popup(filesLst,true)"`

More work is need to make it honor the config setting for printing

**Comment by kneiser** [comment]
1. The the changes:
`edit, this should handle other config options:
'bulk'=>$GLOBALS['Printer'] % 2 == 0?"bulkPrint(this)":"PDF_popup(filesLst,true)",`
I assume that is meant for line 134?
2. After the changes are applied I notice now the single scanned images print button only allows the use of the user's workstation printers? As previously allowing selection of the user workstation printer? and server defined printers? For me that is not an issue, others it might.

**Comment by GM-Script-Writer-62850** [comment]
line 138 not 134
<img src="http://imgur.com/Iu3ikIGl.png"/>

**Comment by kneiser** [comment]
Ok it's all good!

**Comment by GM-Script-Writer-62850** [comment]
Wait it actually worked with a trailing comma... well that is unexpected, normally that would be a syntax error

Also the next update will fix the minor issue of asking to choose a print method when you forget to select files to print
https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/blob/master/res/main.js#L850
`&&files.length>0`

**Comment by kneiser** [comment]
what is line 850 supposed to look liks after the update please?

**Comment by GM-Script-Writer-62850** [comment]
`if(print===true&&files.length>0){`

**Comment by kneiser** [comment]
I did not forget you. I will get to this in the next few days, am tied up with. some other things at the moment. I also had to reinstall the scanner software somehow I managed to corrupt code during pasting, my bad.
