### ISSUE TITLE
Printing to Server CUPS

### ISSUE THREAD

**Issue by kneiser** [GM-Script-Writer-62850/PHP-Scanner-Server#46]
I recently built up a new 64-bit Debian test server to replace an aging 32-bit machine. I've been using the PHP Scanner Server software for sometime now. While building the new machine I decided to install CUPS on the to print to 3 printers; Laser (network), Inkjet (network), and CUPS-PDF driver. I can print a test page with no problems from CUPS (v2.2.10) to the printers.
However when I scan an image then print it to one of the printers only a "top-left" section of the page prints. If I print to CUPS-PDF again the same resulting output. If I go to the command-line and issue an "lp" command  to print the image to one of the printers it prints great! So this seems to me that the scanning software needs to include a "fit-to-page" option issued to CUPS? I have attached a copy of the image with a red box to show the page section that prints. CUPS does not seem to have a default "fit-to-page setting" I have this same problem on my production server.

![Scanned Image](https://user-images.githubusercontent.com/3117010/84216003-6f209500-aa85-11ea-9762-87fa32156761.jpg)
I have attached a screenshot of the printer setting used:
![ScannerSetting300dpi](https://user-images.githubusercontent.com/3117010/84216731-a2642380-aa87-11ea-8561-875de0b30399.png)
I tried different page sizes and get the same output result.
Is there a place in the software to force "fit-to-page" or do you have another suggestion what it could be?

**Comment by GM-Script-Writer-62850** [comment]
I have 3 different print methods
see line 12 of [config.ini](../blob/master/config.ini#L12)
Which method are you using?
![Screenshot_2020-06-09_22-29-47](https://user-images.githubusercontent.com/564653/84220600-2b3b8900-aaa1-11ea-9169-77fc2ddbaebf.png)

**Comment by GM-Script-Writer-62850** [comment]
I tested each method using the cups-pdf printer and was unable to find an issue printing a scanned file
only issue i had was when choosing 'i don't care' i got a error related to this
https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion
and after editing like 94 of /etc/ImageMagick-6/policy.xml it works as expected

**Comment by GM-Script-Writer-62850** [comment]
i somehow broke my pdf printer, also noticed my /var partition is full probably related
ii am blaming snap packages on this, bit i get to move a few hundred gigs around to make the partition larger...
i'll test more after i fix that tomorrow

**Comment by GM-Script-Writer-62850** [comment]
Xubuntu 20.04 unable to reproduce, you said this only happens with large files right?
`cat /etc/php/7.3/apache2/php.ini | grep memory_limit`
since php spawns the lp command it may be subject to the memory limit of php, mine is set to 128M
*Buster uses php 7.3, focal uses php 7.4; i never had issues with php 7.2
here are some other settings that may be different
```
~$ cat /etc/php/7.3/apache2/php.ini | egrep "^(memory_limit|max_execution_time|post_max_size|upload_max_filesize|html_errors|display_errors)"
max_execution_time = 30
memory_limit = 128M
display_errors = On
html_errors = On
post_max_size = 8M
upload_max_filesize = 25M
```

**Comment by kneiser** [comment]
I use php 7.4.

1. I set my php memory limit to 128M no change.
2. I tried disabling PrivateTemp, no change.
3. You said that php spawns lp? I printed the image from the command line using lp and the output on all printers was perfect. I confirmed again from command line and the scanned image prints perfectly.

**Comment by GM-Script-Writer-62850** [comment]
When php runs the [lp command](../blob/master/res/printer.php#L31) it does so from php as www-data, so i would image it has the same permission and memory restrictions
you can try running it like this
`sudo -u www-data lp...`

If you insert this [above like 33 of printer.php](../blob/master/res/printer.php#L33) it will give you a script and a pdf to try to reproduce the issue, both files will be in /tmp (requires PrivateTmp to be disabled, if you want to be able to find it)

```
	@copy($file,"/tmp/WhyDoesItNotWork.pdf");
	$S_file="/tmp/WhyDoesItNotWork.sh";
	$S_file=@fopen($S_file,'w+');
	@fwrite($S_file,'#!/bin/sh'."\n".'sudo -u www-data lp -d '.escapeshellarg($_GET['printer'])." -n $q -o $o /tmp/WhyDoesItNotWork.pdf");
	@fclose($S_file);
```

**Comment by kneiser** [comment]
I have PrivateTmp disabled. Put in the code as provided. Same results.
![printercodeshot](https://user-images.githubusercontent.com/3117010/84410296-2c68d500-abcb-11ea-87af-a332d2a6c062.png)

**Comment by GM-Script-Writer-62850** [comment]
That code will give you file for further debugging, just to be sure nothing fishy is going on, it drops a shell script and a pdf into your server's `/tmp` folder

**Comment by kneiser** [comment]
1. Just to confirm my PrivateTmp setting:
cat /etc/systemd/system/multi-user.target.wants/apache2.service
[Unit]
Description=The Apache HTTP Server
After=network.target remote-fs.target nss-lookup.target
Documentation=https://httpd.apache.org/docs/2.4/

[Service]
Type=forking
Environment=APACHE_STARTED_BY_SYSTEMD=true
ExecStart=/usr/sbin/apachectl start
ExecStop=/usr/sbin/apachectl stop
ExecReload=/usr/sbin/apachectl graceful
PrivateTmp=false
Restart=on-abort

[Install]
WantedBy=multi-user.target
2. I've attached the 2 files from the server tmp directory.
[WhyDoesItNotWorkFiles.zip](https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/files/4766191/WhyDoesItNotWorkFiles.zip)
3. Use case used. Selected printer item in PHP Scanner toolbar, selected the network Laser printer connected to CUPS server. Same problem result.

**Comment by GM-Script-Writer-62850** [comment]
I was not saying you had it on or off, i have had that feature annoy me more than once it really got under my skin the 1st time
does it fail when you run the sh script?

**Comment by kneiser** [comment]
I was just verifying the pretest conditions. No the script did not fail just same output issue.

**Comment by GM-Script-Writer-62850** [comment]
if that game the same useless print but it works without the `sudo -u www-data` I'd say it is a permissions issue
is www-data in the lp group?
`groups www-data`
if so if you put www-data in your user group does it work
```
kneiser@busterServer:~$ groups www-data
www-data : www-data lp kneiser
```

**Comment by kneiser** [comment]
1. www-data is a member of the lp group.
2. added to my group. same issue.

**Comment by GM-Script-Writer-62850** [comment]
Hopefully the cups and cups-pdf log files will tell me something

**Comment by GM-Script-Writer-62850** [comment]
So how did you get it to work for your default user account
I get the same issue with www-data, root, and the user account
`lp -d PDF -n 1 /tmp/WhyDoesItNotWork.pdf`

**Comment by GM-Script-Writer-62850** [comment]
I found a way to fix it, but i want to know how to detect that this is problem or how to make it not a problem, i do not like dirty patches like this
but give this a try
[1.6-18a.zip](https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/files/4768794/1.6-18a.zip)
there is a option in config.ini

**Comment by GM-Script-Writer-62850** [comment]
Think i found a better way than using convert
instead of printing a PDF we print a ps file, this takes the conversion time down from 1.248s to 0.351 seconds
i think i also found out why it took forever to install debian, virtualbox was set to 1 core
Take a look at this:
[patchResultsComparison.zip](https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/files/4770983/patchResultsComparison.zip)

[1.6-18a1.zip](https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/files/4771103/1.6-18a1.zip)

I have changed the BusterPrintBug option from a boolean to a integer where 0 = original, 1 = pdf2ps, and 2 = convert

**Comment by kneiser** [comment]
I reviewed the config.ini. I will try this later today.

**Comment by kneiser** [comment]
Here are my results of printing a scanned image to either a Server network laser printer or CUPS-PDF. Did I test as expected?
**config.ini Settings**

Scenario 1
==========

Printer         = 1
ReplacePrinter  = false
BusterPrintBug  = 1

Same as original issue.

Scenario 2
==========

Printer         = 1
ReplacePrinter  = false
BusterPrintBug  = 2

Same as original issue.

Scenario 3
==========

Printer         = 1
ReplacePrinter  = false
BusterPrintBug  = 0

Same as original issue.

**Comment by GM-Script-Writer-62850** [comment]
Here is me trying to reproduce your issue: [Screencast 2020-06-12 16:34:13.mp4.zip](https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/files/4773126/Screencast.2020-06-12.16.34.13.mp4.zip)
Scenarios 1 and 2 should work while 1 produces a trash bin print
i used the sample image you provided for this test on a clean install of debian buster

**Comment by kneiser** [comment]
**config.ini settings using cups-pdf for output testing**

### Scenario 1

Printer = 1
ReplacePrinter = false
BusterPrintBug = 1

Produced a PDF file. Looks good.

### Scenario 2

Printer = 1
ReplacePrinter = false
BusterPrintBug = 2

Produced a PDF file. However you predicted the output quality is not good.

Did not bother with Scenario 3 as we agree on the result, trash bin

So using the postscript file output provides results using cups-pdf. So what about usecases where a user wants to print a scanned image(s) directly to a CUPS network connected printer?

**Comment by GM-Script-Writer-62850** [comment]
BusterPrintBug = 1 converts the internal PDF to a new PDF and prints said PDF file using the `lp` command
BusterPrintBug = 2 converts the internal PDF to a internal PS (post script) file then prints the PS file using the `lp` command

> So what about usecases where a user wants to print a scanned image(s) directly to a CUPS network connected printer?
You mean just send the image to the printer, the reason i use pdf field in the back end is PDF files print like you would expect, in my exp (until you found this quirk) they just work, now there is the i do not care just print it button which converts the image file to a pdf in full auto mode no rules, no paper sizes, are you saying i should do this? `lp -d PDF ../www-data/php-scanner/scans/file/Scan_0_Jun_10_2020~19-35-11.jpg`

**Comment by GM-Script-Writer-62850** [comment]
I am assuming you are no longer able to get garbage prints with BusterPrintBug > 0
just committed quite a large update with many bug fixes, see the [change log](../wiki/Change-Log) for details

**Comment by kneiser** [comment]
Ok I just installed the new version and did some testing:
1. One page scanned image outputs correctly now when printing directly to a CUPS network connected printer on the server. PDF generates fine too.
2. Bulk printing of multiple scanned images to CUPS connected network printer shows the original problem. However, printing multiple images to the CUPS connected cups-pdf outputs correctly. So is there a separate section in the scanner code for multiple printing that needs to be updated?

**Comment by GM-Script-Writer-62850** [comment]
So bulk printing has a issue but bulk pdf is fine?

**Comment by GM-Script-Writer-62850** [comment]
If that is what you are saying i can't seem to get it to happen

i did however notice something strange, if i download a pdf and use the print in firefox it works fine but if i open it in evince and print it the print is garbage, this is with `BusterPrintBug = 0`

also noticed that `BusterPrintBug = 1` is MUCH better quality while `BusterPrintBug = 2` is horrible, still better than `BusterPrintBug = 0` since there is actually content on the print, my original testing showed `BusterPrintBug = 1` being worse quality than  `BusterPrintBug = 2`

**Comment by kneiser** [comment]
Well for bulk printing I will avoid printing multiple scanned images directly to a server network connected printer. For bulk printing I would mainly use cups-pdf and the output for muliple images is not blank like the original issue.

**Comment by GM-Script-Writer-62850** [comment]
Just pushed a update in that will fix the quality using BusterPrintBug 2
BusterPrintBug theoretically supports values of about 9E18 but if you do something silly like that prepare to run out of system resources or hit some other software limit

**Comment by GM-Script-Writer-62850** [comment]
I just pushed a update that may fix a secondary issue you were having
[commit](https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server/commit/19d282295dfc77f44bfce39c4cf2698a26b362af/#diff-0b4e4440ca96567315a8975174814dab)
basically all the printer options I was sending to lp were formatted wrong so they did nothing
